import React from "react"
import Head from "next/head"
import NavBar from "@/components/dashboard/NavBar"
import { appDetails } from "@/pages/_app"
import HouseCard from "@/components/dashboard/HouseCard"
import Footer from "@/components/dashboard/Footer"
import AreaChart, { IDataSets } from "@/components/dashboard/AreaChart"

const datasets: IDataSets[] = [
  {
    id: 1,
    bill: 300,
    bill_type: "electric",
    month: "jan",
    year: 2023
  },
  {
    id: 2,
    bill: 500,
    bill_type: "electric",
    month: "feb",
    year: 2023
  }
]

const Dashboard = () => {
  return (
    <>
      <Head>
        <title>{appDetails.appName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto min-h-screen bg-purple-200">
        <NavBar />
        <HouseCard />
        <div className="grid grid-cols-1 lg:grid-cols-2 px-4">
          <AreaChart
            datasets={datasets}
            label="Electric"
            color="green"
            fillColor="rgba(23,23,12,0.6)"
          />
          <AreaChart
            datasets={datasets}
            label="Water"
            color="blue"
            fillColor="rgba(23,23,12,0.6)"
          />
        </div>
      </main>
      <Footer />
    </>
  )
}

export default Dashboard
