import React, { useEffect, useState } from "react"
import Head from "next/head"
import NavBar from "@/components/dashboard/NavBar"
import { appDetails } from "@/pages/_app"
import HouseCard from "@/components/dashboard/HouseCard"
import Footer from "@/components/dashboard/Footer"
import AreaChart, { IDataSets } from "@/components/dashboard/AreaChart"
import client from "@/axios/client"
import { AxiosResponse } from "axios"
import getData from "@/axios/getData"
import { useAppDispatch, useAppSelector } from "@/store"
import { getActiveTenants, getAllTenants } from "@/redux/tenantSlice"
import PageLayout from "@/components/dashboard/layouts/PageLayout"

const datasets: IDataSets[] = [
  {
    id: 1,
    bill: 300,
    bill_type: "electric",
    month: "jan",
    year: 2023
  },
  {
    id: 2,
    bill: 500,
    bill_type: "electric",
    month: "feb",
    year: 2023
  }
]

const Dashboard = () => {
  const state = useAppSelector((state) => state.tenants)
  const dispatch = useAppDispatch()
  useEffect(() => {
    dispatch(getActiveTenants())
    dispatch(getAllTenants())
  }, [])

  return (
    <>
      <Head>
        <title>{appDetails.appName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PageLayout title="Dashboard">
          <HouseCard />

          <div className="grid grid-cols-1 lg:grid-cols-2 px-4">
            <AreaChart
              datasets={datasets}
              label="Electric"
              color="green"
              fillColor="rgba(23,23,12,0.6)"
            />
            <AreaChart
              datasets={datasets}
              label="Water"
              color="blue"
              fillColor="rgba(23,23,12,0.6)"
            />
          </div>
        </PageLayout>
      </main>
      <Footer />
    </>
  )
}

export default Dashboard
