import React, { useEffect } from "react"
import Head from "next/head"
import { appDetails } from "@/pages/_app"
import HouseCard from "@/components/dashboard/HouseCard"
import Footer from "@/components/dashboard/Footer"
import AreaChart from "@/components/dashboard/AreaChart"
import getData from "@/axios/getData"
import { useAppDispatch, useAppSelector } from "@/store"
import { getAllTenants, setActiveTenants } from "@/redux/tenantSlice"
import PageLayout from "@/components/dashboard/layouts/PageLayout"
import { IDataSets, IHouse, ITenant } from "@/interfaces"

const datasets: IDataSets[] = [
  {
    id: 1,
    bill: 300,
    bill_type: "electric",
    month: "jan",
    year: 2023
  },
  {
    id: 2,
    bill: 500,
    bill_type: "electric",
    month: "feb",
    year: 2023
  }
]

type IProps = {
  houses: IHouse[]
  activeTenants: ITenant[]
}

const Dashboard = ({ houses, activeTenants }: IProps) => {
  const state = useAppSelector((state) => state.tenants)
  const dispatch = useAppDispatch()
  useEffect(() => {
    dispatch(setActiveTenants(activeTenants))
  }, [])

  console.log({ state, activeTenants })
  return (
    <>
      <Head>
        <title>{appDetails.appName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PageLayout title="Dashboard">
          <HouseCard houses={houses} />

          <div className="grid grid-cols-1 lg:grid-cols-2 px-4">
            <AreaChart
              datasets={datasets}
              label="Electric"
              color="green"
              fillColor="rgba(23,23,12,0.6)"
            />
            <AreaChart
              datasets={datasets}
              label="Water"
              color="blue"
              fillColor="rgba(23,23,12,0.6)"
            />
          </div>
        </PageLayout>
      </main>
      <Footer />
    </>
  )
}

export const getStaticProps = async () => {
  const houses = await getData("/api/houses")
  const activeTenants = await getData("/api/tenants")
  return {
    props: {
      houses,
      activeTenants
    }
  }
}

export default Dashboard
