import React from "react"
import Head from "next/head"
import NavBar from "@/components/dashboard/navbar"
import { appDetails } from "@/pages/_app"
import HouseCard from "@/components/dashboard/HouseCard"
import Footer from "@/components/dashboard/Footer"

const Dashboard = () => {
  return (
    <>
      <Head>
        <title>{appDetails.appName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto min-h-screen bg-purple-200">
        <NavBar />
        <HouseCard />
      </main>
      <Footer />
    </>
  )
}

export default Dashboard
