import Head from "next/head"
import LoginForm from "@/components/LoginForm"
import { appDetails } from "@/pages/_app"

export default function Home() {
  return (
    <>
      <Head>
        <title>{appDetails.appName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[url('/assets/imgs/home-bg.jpg')] bg-fixed bg-cover min-h-screen">
        <div className="">
          <LoginForm />
        </div>
      </main>
    </>
  )
}
